### ISSUE TITLE
GNU LibreJS breaks website

### ISSUE THREAD

**Issue by antimony112** [ilovelampadaire/ilov3lampadairwebsite#4]
GNU LibreJS extension(for firefox) breaks buttons, Fun facts and wallpaper effect

**Comment by Ponali** [comment]
can you try sending some verbose logs from LibreJS and/or media that can help me understand what's going on? i have never heard of LibreJS, since i got used to normal browsers without that extension.

**Comment by antimony112** [comment]
blocked scripts in https://www.ilovelampadaire.com/:

https://www.ilovelampadaire.com/index.js:

External script with no known license

**Comment by antimony112** [comment]
it breaks because ilovelampadaire.com/index.js is not licensed under FOSS licence

**Comment by antimony112** [comment]
the newest commit resolved the issue
